apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: l4i9r9zt9-python 
  janus-idp.io/tekton: l4i9r9zt9-python
  backstage.io/kubernetes-id: l4i9r9zt9-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l4i9r9zt9-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  