apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: l4i9r9zt9-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: l4i9r9zt9-python 
  name: l4i9r9zt9-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: l4i9r9zt9-python 
